<Project Sdk="Aspire.AppHost.Sdk/13.3.5">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>806b851f-1728-4efd-aa72-dec8b8ac69de</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../StoreApp.API/StoreApp.API.csproj" />
    <ProjectReference Include="../StoreApp.Worker/StoreApp.Worker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.3.5" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.3.5" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

</Project>
